# HolyLife Application Configuration

server:
  port: 8080

spring:
  application:
    name: holylife

  # MariaDB DataSource
  datasource:
    url: jdbc:mariadb://localhost:3306/holylife
    driver-class-name: org.mariadb.jdbc.Driver
    username: shaloman
    password: 123321

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

# Logging
logging:
  level:
    org.shaloman.pj: DEBUG
    org.hibernate.SQL: DEBUG